version: '3.1'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - cs452-mysql-data:/var/lib/mysql
    

volumes:
  cs452-mysql-data: